### ISSUE TITLE
Placement rule doesn't have marshal functions

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/netmap-ql#4]
`PlacementRule` structure is placed in DHT in binary form as a `[]byte`, but right now there is no implementation of `Marshal()` and `Unmarshal()` functions.

**Comment by alexvanin** [comment]
Is it better to do it through `protobuf` or implement `MarshalBinary()` manually? cc @im-kulikov

**Comment by fyrchik** [comment]
There is no DHT in this lib. It is better to do serialization, where such functionality is needed, here we only provide parsing result.

**Comment by alexvanin** [comment]
It seems natural to me to implement marshal functions in library and not somewhere outside.
